export const hh19info = {
    name: "HowdyHack 2019",
    link: "/hh/2019",
    logo: "hh19",
    description: "Our fall hackathon nearly triples in size! Over 200 aggies coding the night away with a bunch of activities and mini-events.",
    directors: [
        {
            webp: "./static/assets/headshots/compressed/sophia.webp",
            img: "./static/assets/headshots/compressed/sophia.jpg",
            name: "Sophia Lee",
            position: "President/Logistics Director",
            github: "https://www.github.com/sophialee0416",
            linkedin: "https://www.linkedin.com/in/sophialee0417",
        },
        {
            webp: "./static/assets/headshots/compressed/suvedh.webp",
            img: "./static/assets/headshots/compressed/suvedh.jpg",
            name: "Suvedh Srikanth",
            position: "Finance Director",
            github: "https://www.github.com/suvedhs",
            linkedin: "https://www.linkedin.com/in/suvedh-srikanth",
        },
        {
            webp: "./static/assets/headshots/compressed/grace.webp",
            img: "./static/assets/headshots/compressed/grace.jpg",
            name: "Grace Fan",
            position: "Creative Director",
            github: "https://www.github.com/gracekfan",
            linkedin: "https://www.linkedin.com/in/gracekfan",
        },
        {
            webp: "./static/assets/headshots/compressed/gabriel.webp",
            img: "./static/assets/headshots/compressed/gabriel.jpg",
            name: "Gabriel Britain",
            position: "Tech Lead",
            github: "https://www.github.com/SaltyQuetzals",
            linkedin: "https://www.linkedin.com/in/gabriel-britain-57523214b",
        },
        {
            webp: "./static/assets/headshots/compressed/aman.webp",
            img: "./static/assets/headshots/compressed/aman.jpg",
            name: "Aman Gottumukkala",
            position: "Tech Mentor",
            github: "https://www.github.com/amangotchu",
            linkedin: "https://www.linkedin.com/in/amangotchu",
        },
        {
            webp: "./static/assets/headshots/compressed/derek.webp",
            img: "./static/assets/headshots/compressed/derek.jpg",
            name: "Derek Li",
            position: "Hardware Mentor",
            github: "https://www.github.com/derektli97",
            linkedin: "https://www.linkedin.com/in/derek-li-4910",
        },
        {
            webp: "./static/assets/headshots/compressed/addison.webp",
            img: "./static/assets/headshots/compressed/addison.jpg",
            name: "Addison Maupin",
            position: "Finance Mentor",
            linkedin: "https://www.linkedin.com/in/addison-maupin-73a394131",
        },
        {
            webp: "./static/assets/headshots/compressed/jonathan.webp",
            img: "./static/assets/headshots/compressed/jonathan.jpg",
            name: "Jonathan Innis",
            position: "Design & Tech",
            github: "https://www.github.com/jonathan-innis",
            linkedin: "https://www.linkedin.com/in/jonathan-innis-87581312a",
        },
        {
            webp: "./static/assets/headshots/compressed/maggieV.webp",
            img: "./static/assets/headshots/compressed/maggieV.jpg",
            name: "Maggie von Ebers",
            position: "Finance",
            github: "https://www.github.com/mx60s",
            linkedin: "https://www.linkedin.com/in/maggie-v",
        },
        {
            webp: "./static/assets/headshots/compressed/roesha.webp",
            img: "./static/assets/headshots/compressed/roesha.jpg",
            name: "Roesha Nigos",
            position: "Finance",
            github: "https://www.github.com/roeshanigos",
            linkedin: "https://www.linkedin.com/in/roeshanigos",
        },
        {
            webp: "./static/assets/headshots/compressed/maggieP.webp",
            img: "./static/assets/headshots/compressed/maggieP.jpg",
            name: "Meghana Pothugunta",
            position: "Logistics",
            linkedin: "https://www.linkedin.com/in/meghana-pothugunta-7161a8183",
        },
        {
            webp: "./static/assets/headshots/compressed/anthony.webp",
            img: "./static/assets/headshots/compressed/anthony.jpg",
            name: "Anthony Teo",
            position: "Design",
            github: "https://www.github.com/eightants",
            linkedin: "https://www.linkedin.com/in/anthonyteo",
        },
        {
            webp: "./static/assets/headshots/compressed/nathan.webp",
            img: "./static/assets/headshots/compressed/nathan.jpg",
            name: "Nathan Reddy",
            position: "Tech",
            github: "https://www.github.com/onewebdev",
            linkedin: "https://www.linkedin.com/in/nathan-r-profile",
        },
        {
            webp: "./static/assets/headshots/compressed/marissa.webp",
            img: "./static/assets/headshots/compressed/marissa.jpg",
            name: "Marissa Soria",
            position: "Logistics",
            github: "https://www.github.com/soriamarissa",
            linkedin: "https://www.linkedin.com/in/marissa-soria-233b8914b",
        },
        {
            webp: "./static/assets/headshots/compressed/ledet.webp",
            img: "./static/assets/headshots/compressed/ledet.jpg",
            name: "Ledet Awano",
            position: "Finance",
            github: "https://www.github.com/ledet2020",
            linkedin: "https://www.linkedin.com/in/ledet-awano",
        },
        {
            webp: "./static/assets/headshots/compressed/humza.webp",
            img: "./static/assets/headshots/compressed/humza.jpg",
            name: "Humza Jaffri",
            position: "Finance",
            github: "https://www.github.com/HumzaJaffri",
            linkedin: "https://www.linkedin.com/in/humza-jaffri-b5089299",
        },
        {
            webp: "./static/assets/headshots/compressed/cameron.webp",
            img: "./static/assets/headshots/compressed/cameron.jpg",
            name: "Cameron Coffey",
            position: "Tech",
            github: "https://www.github.com/cameron3301",
            linkedin: "https://www.linkedin.com/in/cameron-coffey-0018b614a",
        },
        {
            webp: "./static/assets/headshots/compressed/aryan.webp",
            img: "./static/assets/headshots/compressed/aryan.jpg",
            name: "Aryan Shetty",
            position: "Logistics",
            github: "https://www.github.com/aryanshetty711",
            linkedin: "https://www.linkedin.com/in/aryan-shetty-860717148",
        },
        {
            webp: "./static/assets/headshots/compressed/reuben.webp",
            img: "./static/assets/headshots/compressed/reuben.jpg",
            name: "Reuben Tadpatri",
            position: "Logistics",
            github: "https://www.github.com/rstadpatri",
            linkedin: "https://www.linkedin.com/in/reuben-tadpatri-9baab214b",
        },
        {
            webp: "./static/assets/headshots/compressed/jay.webp",
            img: "./static/assets/headshots/compressed/jay.jpg",
            name: "Jay Khatri",
            position: "Tech",
            github: "https://www.github.com/jay-khatri",
            linkedin: "https://www.linkedin.com/in/jay-khatri",
        },
    ],
}
