export const hh20info = {
    name: 'HowdyHack 2020',
    link: '/hh/2020',
    logo: 'hh20',
    description: 'Our fall hackathon!',
    directors: [
        {
            webp: './static/assets/headshots/compressed/humza.webp',
            img: './static/assets/headshots/compressed/humza.jpg',
            name: 'Humza Jaffri',
            position: 'President',
            github: 'https://github.com/HumzaJaffri',
            linkedin: 'https://www.linkedin.com/in/humza-jaffri-b5089299',
        },
        {
            webp: './static/assets/headshots/compressed/marissa.webp',
            img: './static/assets/headshots/compressed/marissa.jpg',
            name: 'Marissa Soria',
            position: 'Vice President',
            github: 'https://github.com/soriamarissa',
            linkedin: 'https://www.linkedin.com/in/marissa-soria-233b8914b',
        },
        {
            webp: './static/assets/headshots/compressed/anthony.webp',
            img: './static/assets/headshots/compressed/anthony.jpg',
            name: 'Anthony Teo',
            position: 'Design Lead',
            github: 'https://github.com/eightants',
            linkedin: 'https://www.linkedin.com/in/anthonyteo',
        },
        {
            webp: './static/assets/headshots/compressed/cameronB2.webp',
            img: './static/assets/headshots/compressed/cameronB2.jpg',
            name: 'Cameron Brill',
            position: 'Tech Lead',
            github: 'https://github.com/cameronbrill',
            linkedin: 'https://www.linkedin.com/in/cameronbrill',
        },
        {
            webp: './static/assets/headshots/compressed/aman.webp',
            img: './static/assets/headshots/compressed/aman.jpg',
            name: 'Aman Gottumukkala',
            position: 'Tech Mentor',
            github: 'https://github.com/amangotchu',
            linkedin: 'https://www.linkedin.com/in/amangotchu',
        },
        {
            webp: './static/assets/headshots/compressed/maggieP.webp',
            img: './static/assets/headshots/compressed/maggieP.jpg',
            name: 'Meghana Pothugunta',
            position: 'Logistics',
            linkedin:
                'https://www.linkedin.com/in/meghana-pothugunta-7161a8183',
        },
        {
            webp: './static/assets/headshots/compressed/nathan.webp',
            img: './static/assets/headshots/compressed/nathan.jpg',
            name: 'Nathan Reddy',
            position: 'Tech',
            github: 'https://github.com/onewebdev',
            linkedin: 'https://www.linkedin.com/in/nathan-r-profile',
        },
        {
            webp: './static/assets/headshots/compressed/aryan.webp',
            img: './static/assets/headshots/compressed/aryan.jpg',
            name: 'Aryan Shetty',
            position: 'Logistics',
            github: 'https://github.com/aryanshetty711',
            linkedin: 'https://www.linkedin.com/in/aryan-shetty-860717148',
        },
        {
            webp: './static/assets/headshots/compressed/vivian.webp',
            img: './static/assets/headshots/compressed/vivian.jpg',
            name: 'Vivian Yu',
            position: 'Design',
            github: 'https://github.com/vivians-y',
            linkedin: 'https://www.linkedin.com/in/vivianyus/',
        },
        {
            webp: './static/assets/headshots/compressed/clay.webp',
            img: './static/assets/headshots/compressed/clay.jpg',
            name: 'Clay Juneau',
            position: 'Design',
            github: 'https://github.com/clayjuneau',
            linkedin: 'https://www.linkedin.com/in/clayjuneau',
        },
        {
            webp: './static/assets/headshots/compressed/nathanR.webp',
            img: './static/assets/headshots/compressed/nathanR.jpg',
            name: 'Nathan Read',
            position: 'Tech',
            github: 'https://github.com/nathancread',
            linkedin: 'https://www.linkedin.com/in/nathancread',
        },
        {
            webp: './static/assets/headshots/compressed/adil.webp',
            img: './static/assets/headshots/compressed/adil.jpg',
            name: 'Adil Rasiyani',
            position: 'Tech',
            github: 'https://github.com/AdilRas',
            linkedin: 'https://www.linkedin.com/in/adil-rasiyani',
        },
        {
            webp: './static/assets/headshots/compressed/dylan.webp',
            img: './static/assets/headshots/compressed/dylan.jpg',
            name: 'Dylan Theriot',
            position: 'Tech',
            github: 'https://github.com/dylantheriot',
            linkedin: 'https://www.linkedin.com/in/dylan-theriot',
        },
        {
            webp: './static/assets/headshots/compressed/yashas.webp',
            img: './static/assets/headshots/compressed/yashas.jpg',
            name: 'Yashas Salankimatt',
            position: 'Hardware',
            github: 'https://github.com/yashas-salankimatt',
            linkedin: 'https://www.linkedin.com/in/yashas-s',
        },
        {
            webp: './static/assets/headshots/compressed/joanna.webp',
            img: './static/assets/headshots/compressed/joanna.jpg',
            name: 'Joanna Zhou',
            position: 'Logistics',
            github: 'https://github.com/jo-zho',
            linkedin: 'https://www.linkedin.com/in/joannazhou-tamu',
        },
        {
            webp: './static/assets/headshots/compressed/anikait.webp',
            img: './static/assets/headshots/compressed/anikait.jpg',
            name: 'Anikait Sharma',
            position: 'Tech & Logistics',
            github: 'https://github.com/anikait627',
            linkedin: 'https://www.linkedin.com/in/anikait',
        },
        {
            webp: './static/assets/headshots/compressed/rohit.webp',
            img: './static/assets/headshots/compressed/rohit.jpg',
            name: 'Rohit Barichello',
            position: 'Logistics',
            github: 'https://github.com/rohitbarichello',
            linkedin: 'https://www.linkedin.com/in/rohitbarichello',
        },
        {
            webp: './static/assets/headshots/compressed/sabrina.webp',
            img: './static/assets/headshots/compressed/sabrina.jpg',
            name: 'Sabrina Lu',
            position: 'Logistics',
            github: 'https://github.com/sabrinalu999',
            linkedin: 'https://www.linkedin.com/in/sabrinamjlu',
        },
        {
            webp: './static/assets/headshots/compressed/ricky.webp',
            img: './static/assets/headshots/compressed/ricky.jpg',
            name: 'Ricky Bengani',
            position: 'Design',
            linkedin: 'https://www.linkedin.com/in/rickybengani',
        },
    ],
};
