export const hh25info = {
    name: 'HowdyHack 2025',
    link: '/hh/2025',
    photos: 'https://tx.ag/hh25photos',
    logo: 'hh25',
    description: "Reinventing the wheel at HowdyHack '25!",
    directors: [
        {
            webp: './static/hh-2025/headshots/webp/adam.webp',
            img: './static/hh-2025/headshots/jpg/adam.jpg',
            party: './static/hh-2025/headshots/party/adam.webp',
            name: 'Adam Teo',
            position: 'President',
            github: 'https://github.com/ysadamt',
            linkedin: 'https://www.linkedin.com/in/ysadamt/',
            portfolio: 'http://ysadamt.com/',
        },
        {
            webp: './static/hh-2025/headshots/webp/rita.webp',
            img: './static/hh-2025/headshots/jpg/rita.jpg',
            party: './static/hh-2025/headshots/party/rita.webp',
            name: 'Rita Hernandez Guerrero',
            position: 'Vice President',
            linkedin:
                'https://www.linkedin.com/in/rita-hernandez-guerrero-1a59831ba',
        },
        {
            webp: './static/hh-2025/headshots/webp/monish.webp',
            img: './static/hh-2025/headshots/jpg/monish.jpg',
            party: './static/hh-2025/headshots/party/monish.webp',
            name: 'Monish Kanneboina',
            position: 'Treasurer',
            linkedin: 'https://www.linkedin.com/in/monish-kanneboina/',
        },
        {
            webp: './static/hh-2025/headshots/webp/annie.webp',
            img: './static/hh-2025/headshots/jpg/annie.jpg',
            party: './static/hh-2025/headshots/party/annie.webp',
            name: 'Annie Li',
            position: 'Creative Lead',
            linkedin: 'https://www.linkedin.com/in/liannie3/',
            portfolio: 'https://liannie.app/',
        },
        {
            webp: './static/hh-2025/headshots/webp/eric.webp',
            img: './static/hh-2025/headshots/jpg/eric.jpg',
            party: './static/hh-2025/headshots/party/eric.webp',
            name: 'Eric Li',
            position: 'Tech Lead',
            github: 'https://github.com/ericli18',
            linkedin: 'https://www.linkedin.com/in/ericli18/',
            portfolio: 'https://ericwuli.com/',
        },
        {
            webp: './static/hh-2025/headshots/webp/nicolas.webp',
            img: './static/hh-2025/headshots/jpg/nicolas.jpg',
            party: './static/hh-2025/headshots/party/nicolas.webp',
            name: 'Nicolas Romero',
            position: 'Logistics Lead',
            github: 'https://github.com/nicolas-m-romero',
            linkedin: 'https://www.linkedin.com/in/nicolas-romero-313151256/',
            portfolio: 'https://nico-romero.com/',
        },
        {
            webp: './static/hh-2025/headshots/webp/nikita.webp',
            img: './static/hh-2025/headshots/jpg/nikita.jpg',
            party: './static/hh-2025/headshots/party/nikita.webp',
            name: 'Nikita Kelwada',
            position: 'Logistics Lead',
            linkedin: 'https://www.linkedin.com/in/nikita-kelwada/',
        },
        {
            webp: './static/hh-2025/headshots/webp/nafi.webp',
            img: './static/hh-2025/headshots/jpg/nafi.jpg',
            party: './static/hh-2025/headshots/party/nafi.webp',
            name: 'Nafi Islam',
            position: 'Logistics',
            github: 'https://github.com/nafi-islam',
            linkedin: 'https://www.linkedin.com/in/nafiislam',
            portfolio: 'https://www.nafiislam.com',
        },
        {
            webp: './static/hh-2025/headshots/webp/harshitha.webp',
            img: './static/hh-2025/headshots/jpg/harshitha.jpg',
            party: './static/hh-2025/headshots/party/harshitha.webp',
            name: 'Harshitha Marepally',
            position: 'Logistics',
            linkedin: 'https://www.linkedin.com/in/harshithamarepally/',
        },
        {
            webp: './static/hh-2025/headshots/webp/katherine.webp',
            img: './static/hh-2025/headshots/jpg/katherine.jpg',
            party: './static/hh-2025/headshots/party/katherine.webp',
            name: 'Katherine Nguyen',
            position: 'Creative',
        },
        {
            webp: './static/hh-2025/headshots/webp/sandeep.webp',
            img: './static/hh-2025/headshots/jpg/sandeep.jpg',
            party: './static/hh-2025/headshots/party/sandeep.webp',
            name: 'Sandeep Kandrigi',
            position: 'Tech',
            github: 'https://github.com/skandrigi',
            linkedin: 'https://www.linkedin.com/in/skandrigi/',
            portfolio: 'https://www.sandeepkandrigi.dev/',
        },
        {
            webp: './static/hh-2025/headshots/webp/nmesoma.webp',
            img: './static/hh-2025/headshots/jpg/nmesoma.jpg',
            party: './static/hh-2025/headshots/party/nmesoma.webp',
            name: 'Nmesoma Duru',
            position: 'Creative',
            linkedin: 'https://www.linkedin.com/in/nmesoma-duru-283b15257/',
        },
        {
            webp: './static/hh-2025/headshots/webp/aj.webp',
            img: './static/hh-2025/headshots/jpg/aj.jpg',
            party: './static/hh-2025/headshots/party/aj.webp',
            name: 'A.J Bamgbelu',
            position: 'Tech',
            linkedin: 'https://www.linkedin.com/in/ajbamgbelu/',
        },
        {
            webp: './static/hh-2025/headshots/webp/ashlee.webp',
            img: './static/hh-2025/headshots/jpg/ashlee.jpg',
            party: './static/hh-2025/headshots/party/ashlee.webp',
            name: 'Ashlee Ajala',
            position: 'Logistics',
            linkedin: 'https://www.linkedin.com/in/ashleeajala/',
        },
        {
            webp: './static/hh-2025/headshots/webp/claire.webp',
            img: './static/hh-2025/headshots/jpg/claire.jpg',
            party: './static/hh-2025/headshots/party/claire.webp',
            name: 'Claire Wang',
            position: 'Creative',
            linkedin: 'https://www.linkedin.com/in/chaire/',
        },
        {
            webp: './static/hh-2025/headshots/webp/keshav.webp',
            img: './static/hh-2025/headshots/jpg/keshav.jpg',
            party: './static/hh-2025/headshots/party/keshav.webp',
            name: 'Keshav Dharshan',
            position: 'Logistics',
            linkedin: 'https://www.linkedin.com/in/keshav-dharshan-35a47524b/',
            github: 'https://github.com/kdharshan0',
            portfolio: 'https://keshavdharshan.com/',
        },
        {
            webp: './static/hh-2025/headshots/webp/blessing.webp',
            img: './static/hh-2025/headshots/jpg/blessing.jpg',
            party: './static/hh-2025/headshots/party/blessing.webp',
            name: 'Blessing Onuoha',
            position: 'Creative',
            linkedin: 'https://www.linkedin.com/in/blxessing/',
        },
        {
            webp: './static/hh-2025/headshots/webp/justin.webp',
            img: './static/hh-2025/headshots/jpg/justin.jpg',
            party: './static/hh-2025/headshots/party/justin.webp',
            name: 'Justin Le',
            position: 'Tech',
            github: 'https://github.com/Ju5t1nL3',
            linkedin: 'https://www.linkedin.com/in/justindtle/',
        },
        {
            webp: './static/hh-2025/headshots/webp/abhi.webp',
            img: './static/hh-2025/headshots/jpg/abhi.jpg',
            party: './static/hh-2025/headshots/party/abhi.webp',
            name: 'Abhitej Devireddy',
            position: 'Logistics',
            linkedin:
                'https://www.linkedin.com/in/abhitej-devireddy-648864275/',
        },
        {
            webp: './static/hh-2025/headshots/webp/ananya.webp',
            img: './static/hh-2025/headshots/jpg/ananya.jpg',
            party: './static/hh-2025/headshots/party/ananya.webp',
            name: 'Ananya Pal',
            position: 'Logistics',
            linkedin: 'https://www.linkedin.com/in/ananya-pal-ap810/',
        },
        {
            webp: './static/hh-2025/headshots/webp/bella.webp',
            img: './static/hh-2025/headshots/jpg/bella.jpg',
            party: './static/hh-2025/headshots/party/bella.webp',
            name: 'Bella Roy',
            position: 'Creative',
            linkedin: 'https://www.linkedin.com/in/isabella-roy-5a3720337/',
        },
        {
            webp: './static/hh-2025/headshots/webp/ben.webp',
            img: './static/hh-2025/headshots/jpg/ben.jpg',
            party: './static/hh-2025/headshots/party/ben.webp',
            name: 'Ben Hardy',
            position: 'Tech',
            github: 'https://github.com/benjaminhardy28',
            linkedin: 'https://www.linkedin.com/in/benhardy4/',
            portfolio: 'https://benhardyportfolio.com/',
        },
        {
            webp: './static/hh-2025/headshots/webp/jashith.webp',
            img: './static/hh-2025/headshots/jpg/jashith.jpg',
            party: './static/hh-2025/headshots/party/jashith.webp',
            name: 'Jashith Raghavendra',
            github: 'https://github.com/jashith1/',
            position: 'Tech',
            linkedin: 'https://www.linkedin.com/in/jashith1/',
        },
        {
            webp: './static/hh-2025/headshots/webp/katelyn.webp',
            img: './static/hh-2025/headshots/jpg/katelyn.jpg',
            party: './static/hh-2025/headshots/party/katelyn.webp',
            name: 'Katelyn Ta',
            position: 'Creative',
        },
        {
            webp: './static/hh-2025/headshots/webp/shaan.webp',
            img: './static/hh-2025/headshots/jpg/shaan.jpg',
            party: './static/hh-2025/headshots/party/shaan.webp',
            name: 'Shaan Charolia',
            position: 'Logistics',
            linkedin: 'https://www.linkedin.com/in/shaancharolia/',
        },
        {
            webp: './static/hh-2025/headshots/webp/veronica.webp',
            img: './static/hh-2025/headshots/jpg/veronica.jpg',
            party: './static/hh-2025/headshots/party/veronica.webp',
            name: 'Veronica Sibal',
            position: 'Logistics',
            linkedin: 'https://www.linkedin.com/in/veronicasibal/',
        },
        {
            webp: './static/hh-2025/headshots/webp/william.webp',
            img: './static/hh-2025/headshots/jpg/william.jpg',
            party: './static/hh-2025/headshots/party/william.webp',
            name: 'William Lam',
            position: 'Logistics',
            linkedin: 'https://www.linkedin.com/in/swwilliamlam/',
        },
    ],
};
