export const th25info = {
    name: 'TAMUhack 2025',
    link: '/th/2025',
    photos: 'https://drive.google.com/drive/folders/1Sf_Zdt9knGTZcke8JuIMM2hu83t-OiE6',
    logo: 'th25',
    description:
        "Next stop: TAMUhack '25, with our first week-long hardware hackathon!",
    directors: [
        {
            webp: './static/th-2025/headshots/webp/li.webp',
            img: './static/th-2025/headshots/jpg/li.jpg',
            party: './static/th-2025/headshots/party/li.png',
            name: 'Li Shen',
            position: 'President',
            linkedin: 'https://www.linkedin.com/in/lililogan/',
            portfolio: 'https://lishen.app/',
        },
        {
            webp: './static/th-2025/headshots/webp/anish.webp',
            img: './static/th-2025/headshots/jpg/anish.jpg',
            party: './static/th-2025/headshots/party/anish.png',
            name: 'Anish Karthik',
            position: 'President',
            github: 'https://github.com/anishfish2',
            linkedin: 'https://www.linkedin.com/in/anishkarthik',
        },
        {
            webp: './static/th-2025/headshots/webp/gabrielle.webp',
            img: './static/th-2025/headshots/jpg/gabrielle.jpg',
            party: './static/th-2025/headshots/party/gabrielle.png',
            name: 'Gabrielle Anne Irava',
            position: 'Secretary & Treasurer',
            linkedin: 'https://www.linkedin.com/in/gairava/',
        },
        {
            webp: './static/th-2025/headshots/webp/naveen.webp',
            img: './static/th-2025/headshots/jpg/naveen.jpg',
            party: './static/th-2025/headshots/party/naveen.png',
            name: 'Naveen Iyer',
            position: 'Tech Lead',
            github: 'https://github.com/NitroGuy10',
            linkedin: 'https://www.linkedin.com/in/naveen-iyer-66412b225/',
            portfolio: 'https://nitroguy.xyz/',
        },
        {
            webp: './static/th-2025/headshots/webp/nafi.webp',
            img: './static/th-2025/headshots/jpg/nafi.jpg',
            party: './static/th-2025/headshots/party/nafi.png',
            name: 'Nafi Islam',
            position: 'Logistics Lead',
            github: 'https://github.com/nafi-islam',
            linkedin: 'https://www.linkedin.com/in/nafiislam',
            portfolio: 'https://www.nafiislam.com',
        },
        {
            webp: './static/th-2025/headshots/webp/joshua.webp',
            img: './static/th-2025/headshots/jpg/joshua.jpg',
            party: './static/th-2025/headshots/party/joshua.png',
            name: 'Joshua John',
            position: 'Logistics Lead',
            linkedin: 'https://www.linkedin.com/in/joshua-john-1055b8240',
        },
        {
            webp: './static/th-2025/headshots/webp/lizzy.webp',
            img: './static/th-2025/headshots/jpg/lizzy.jpg',
            party: './static/th-2025/headshots/party/lizzy.png',
            name: 'Lizzy Yoon',
            position: 'Creative Lead',
            linkedin: 'https://www.linkedin.com/in/lizzy-yoon/',
        },
        {
            webp: './static/th-2025/headshots/webp/ashrita.webp',
            img: './static/th-2025/headshots/jpg/ashrita.jpg',
            party: './static/th-2025/headshots/party/ashrita.png',
            name: 'Ashrita Vadlapatla',
            position: 'Logistics',
            linkedin: 'https://www.linkedin.com/in/ashrita-vadlapatla/',
        },
        {
            webp: './static/th-2025/headshots/webp/adnan.webp',
            img: './static/th-2025/headshots/jpg/adnan.jpg',
            party: './static/th-2025/headshots/party/adnan.png',
            name: 'Adnan Yusuf',
            position: 'Creative',
            github: 'https://github.com/adnanysf',
            linkedin: 'https://www.linkedin.com/in/adnyusuf/',
            portfolio: 'https://www.adnan-yusuf.com/',
        },
        {
            webp: './static/th-2025/headshots/webp/austin.webp',
            img: './static/th-2025/headshots/jpg/austin.jpg',
            party: './static/th-2025/headshots/party/austin.png',
            name: 'Austin Abraham',
            position: 'Logistics',
            linkedin: 'https://www.linkedin.com/in/abaustinva',
        },
        {
            webp: './static/th-2025/headshots/webp/rita.webp',
            img: './static/th-2025/headshots/jpg/rita.jpg',
            party: './static/th-2025/headshots/party/rita.png',
            name: 'Rita Hernandez Guerrero',
            position: 'Logistics',
            linkedin:
                'https://www.linkedin.com/in/rita-hernandez-guerrero-1a59831ba',
        },
        {
            webp: './static/th-2025/headshots/webp/adam.webp',
            img: './static/th-2025/headshots/jpg/adam.jpg',
            party: './static/th-2025/headshots/party/adam.png',
            name: 'Adam Teo',
            position: 'Tech',
            github: 'https://github.com/ysadamt',
            linkedin: 'https://www.linkedin.com/in/ysadamt/',
            portfolio: 'http://ysadamt.com/',
        },
        {
            webp: './static/th-2025/headshots/webp/harshitha.webp',
            img: './static/th-2025/headshots/jpg/harshitha.jpg',
            party: './static/th-2025/headshots/party/harshitha.png',
            name: 'Harshitha Marepally',
            position: 'Logistics',
            linkedin: 'https://www.linkedin.com/in/harshithamarepally/',
        },
        {
            webp: './static/th-2025/headshots/webp/nicolas.webp',
            img: './static/th-2025/headshots/jpg/nicolas.jpg',
            party: './static/th-2025/headshots/party/nicolas.png',
            name: 'Nicolas Romero',
            position: 'Logistics',
            github: 'https://github.com/nicolas-m-romero',
            linkedin: 'https://www.linkedin.com/in/nicolas-romero-313151256/',
            portfolio: 'https://nico-romero.com/',
        },
        {
            webp: './static/th-2025/headshots/webp/sandeep.webp',
            img: './static/th-2025/headshots/jpg/sandeep.jpg',
            party: './static/th-2025/headshots/party/sandeep.png',
            name: 'Sandeep Kandrigi',
            position: 'Tech',
            github: 'https://github.com/skandrigi',
            linkedin: 'https://www.linkedin.com/in/skandrigi/',
            portfolio: 'https://www.sandeepkandrigi.dev/',
        },
        {
            webp: './static/th-2025/headshots/webp/annie.webp',
            img: './static/th-2025/headshots/jpg/annie.jpg',
            party: './static/th-2025/headshots/party/annie.png',
            name: 'Annie Li',
            position: 'Creative',
            linkedin: 'https://www.linkedin.com/in/liannie3/',
            portfolio: 'https://liannie.app/',
        },
        {
            webp: './static/th-2025/headshots/webp/nmesoma.webp',
            img: './static/th-2025/headshots/jpg/nmesoma.jpg',
            party: './static/th-2025/headshots/party/nmesoma.png',
            name: 'Nmesoma Duru',
            position: 'Creative',
            linkedin: 'https://www.linkedin.com/in/nmesoma-duru-283b15257/',
        },
        {
            webp: './static/th-2025/headshots/webp/eric.webp',
            img: './static/th-2025/headshots/jpg/eric.jpg',
            party: './static/th-2025/headshots/party/eric.png',
            name: 'Eric Li',
            position: 'Tech',
            github: 'https://github.com/ericli18',
            linkedin: 'https://www.linkedin.com/in/ericli18/',
            portfolio: 'https://ericwuli.com/',
        },
        {
            webp: './static/th-2025/headshots/webp/aj.webp',
            img: './static/th-2025/headshots/jpg/aj.jpg',
            party: './static/th-2025/headshots/party/aj.png',
            name: 'A.J Bamgbelu',
            position: 'Tech',
            github: 'https://github.com/8SK3PS8',
            linkedin: 'https://www.linkedin.com/in/ajbamgbelu/',
            portfolio: 'https://adeobam.com/',
        },
        {
            webp: './static/th-2025/headshots/webp/ashlee.webp',
            img: './static/th-2025/headshots/jpg/ashlee.jpg',
            party: './static/th-2025/headshots/party/ashlee.png',
            name: 'Ashlee Ajala',
            position: 'Logistics',
            linkedin: 'https://www.linkedin.com/in/ashleeajala/',
        },
        {
            webp: './static/th-2025/headshots/webp/claire.webp',
            img: './static/th-2025/headshots/jpg/claire.jpg',
            party: './static/th-2025/headshots/party/claire.png',
            name: 'Claire Wang',
            position: 'Creative',
            linkedin: 'https://www.linkedin.com/in/chaire/',
        },
        {
            webp: './static/th-2025/headshots/webp/keshav.webp',
            img: './static/th-2025/headshots/jpg/keshav.jpg',
            party: './static/th-2025/headshots/party/keshav.png',
            name: 'Keshav Dharshan',
            position: 'Logistics',
            linkedin: 'https://www.linkedin.com/in/keshav-dharshan-35a47524b/',
            github: 'https://github.com/kdharshan0',
            portfolio: 'https://keshavdharshan.com/',
        },
        {
            webp: './static/th-2025/headshots/webp/monish.webp',
            img: './static/th-2025/headshots/jpg/monish.jpg',
            party: './static/th-2025/headshots/party/monish.png',
            name: 'Monish Kanneboina',
            position: 'Logistics',
            linkedin: 'https://www.linkedin.com/in/monish-kanneboina/',
        },
        {
            webp: './static/th-2025/headshots/webp/nikita.webp',
            img: './static/th-2025/headshots/jpg/nikita.jpg',
            party: './static/th-2025/headshots/party/nikita.png',
            name: 'Nikita Kelwada',
            position: 'Logistics',
            linkedin: 'https://www.linkedin.com/in/nikita-kelwada/',
        },
        {
            webp: './static/th-2025/headshots/webp/blessing.webp',
            img: './static/th-2025/headshots/jpg/blessing.jpg',
            party: './static/th-2025/headshots/party/blessing.png',
            name: 'Blessing Onuoha',
            position: 'Creative',
            linkedin: 'https://www.linkedin.com/in/blxessing/',
        },
        {
            webp: './static/th-2025/headshots/webp/justin.webp',
            img: './static/th-2025/headshots/jpg/justin.jpg',
            party: './static/th-2025/headshots/party/justin.png',
            name: 'Justin Le',
            position: 'Tech',
            github: 'https://github.com/Ju5t1nL3',
            linkedin: 'https://www.linkedin.com/in/justindtle/',
        },
    ],
};
