const th25info = {
    name: "TAMUhack 2025",
    link: "/th/2025",
    photos:
        "https://drive.google.com/drive/folders/1Sf_Zdt9knGTZcke8JuIMM2hu83t-OiE6",
    logo: "th25",
    description:
        "Next stop: TAMUhack '25, with our first week-long hardware hackathon!",
    directors: [
        {
            webp: "./static/th-2025/headshots/webp/li.webp",
            img: "./static/th-2025/headshots/jpg/li.jpg",
            name: "Li Shen",
            position: "President",
            linkedin: "https://www.linkedin.com/in/lililogan/",
            portfolio: "https://lishen.app/",
        },
        {
            webp: "./static/hh-2024/headshots/webp/anish.webp",
            img: "./static/hh-2024/headshots/jpg/anish.jpg",
            name: "Anish Karthik",
            position: "President",
            github: "https://github.com/anishfish2",
            linkedin: "https://www.linkedin.com/in/anishkarthik",
        },
        {
            webp: "./static/th-2025/headshots/webp/gabrielle.webp",
            img: "./static/th-2025/headshots/jpg/gabrielle.jpg",
            name: "Gabrielle Anne Irava",
            position: "Secretary & Treasurer",
            linkedin: "https://www.linkedin.com/in/gairava/",
        },
        {
            webp: "./static/th-2025/headshots/webp/naveen.webp",
            img: "./static/th-2025/headshots/jpg/naveen.jpg",
            name: "Naveen Iyer",
            position: "Tech Lead",
            github: "https://github.com/NitroGuy10",
            linkedin: "https://www.linkedin.com/in/naveen-iyer-66412b225/",
            portfolio: "https://nitroguy.xyz/",
        },
        {
            webp: "./static/th-2025/headshots/webp/nafi.webp",
            img: "./static/th-2025/headshots/jpg/nafi.jpg",
            name: "Nafi Islam",
            position: "Logistics Lead",
            github: "https://github.com/nafi-islam",
            linkedin: "https://www.linkedin.com/in/nafiislam",
            portfolio: "https://www.nafiislam.com",
        },
        {
            webp: "./static/th-2025/headshots/webp/joshua.webp",
            img: "./static/th-2025/headshots/jpg/joshua.jpg",
            name: "Joshua John",
            position: "Logistics Lead",
            linkedin: "https://www.linkedin.com/in/joshua-john-1055b8240",
        },
        {
            webp: "./static/th-2025/headshots/webp/lizzy.webp",
            img: "./static/th-2025/headshots/jpg/lizzy.jpg",
            name: "Lizzy Yoon",
            position: "Creative Lead",
            linkedin: "https://www.linkedin.com/in/lizzy-yoon/",
        },
        {
            webp: "./static/th-2025/headshots/webp/ashrita.webp",
            img: "./static/th-2025/headshots/jpg/ashrita.jpg",
            name: "Ashrita Vadlapatla",
            position: "Logistics",
            linkedin: "https://www.linkedin.com/in/ashrita-vadlapatla/",
        },
        {
            webp: "./static/th-2025/headshots/webp/adnan.webp",
            img: "./static/th-2025/headshots/jpg/adnan.jpg",
            name: "Adnan Yusuf",
            position: "Creative",
            github: "https://github.com/adnanysf",
            linkedin: "https://www.linkedin.com/in/adnyusuf/",
            portfolio: "https://www.adnan-yusuf.com/",
        },
        {
            webp: "./static/th-2025/headshots/webp/austin.webp",
            img: "./static/th-2025/headshots/jpg/austin.jpg",
            name: "Austin Abraham",
            position: "Logistics",
            linkedin: "https://www.linkedin.com/in/abaustinva",
        },
        {
            webp: "./static/th-2025/headshots/webp/rita.webp",
            img: "./static/th-2025/headshots/jpg/rita.jpg",
            name: "Rita Hernandez Guerrero",
            position: "Logistics",
            linkedin: "https://www.linkedin.com/in/rita-hernandez-guerrero-1a59831ba",
        },
        {
            webp: "./static/th-2025/headshots/webp/adam.webp",
            img: "./static/th-2025/headshots/jpg/adam.jpg",
            name: "Adam Teo",
            position: "Tech",
            github: "https://github.com/ysadamt",
            linkedin: "https://www.linkedin.com/in/ysadamt/",
            portfolio: "http://ysadamt.com/",
        },
        {
            webp: "./static/th-2025/headshots/webp/harshitha.webp",
            img: "./static/th-2025/headshots/jpg/harshitha.jpg",
            name: "Harshitha Marepally",
            position: "Logistics",
            linkedin: "https://www.linkedin.com/in/harshithamarepally/",
        },
        {
            webp: "./static/th-2025/headshots/webp/nicolas.webp",
            img: "./static/th-2025/headshots/jpg/nicolas.jpg",
            name: "Nicolas Romero",
            position: "Logistics",
            linkedin: "https://www.linkedin.com/in/nicolas-romero-313151256/",
        },
        {
            webp: "./static/th-2025/headshots/webp/sandeep.webp",
            img: "./static/th-2025/headshots/jpg/sandeep.jpg",
            name: "Sandeep Kandrigi",
            position: "Tech",
            github: "https://github.com/skandrigi",
            linkedin: "https://www.linkedin.com/in/skandrigi/",
            portfolio: "https://www.sandeepkandrigi.dev/",
        },
        {
            webp: "./static/th-2025/headshots/webp/annie.webp",
            img: "./static/th-2025/headshots/jpg/annie.jpg",
            name: "Annie Li",
            position: "Creative",
            linkedin: "https://www.linkedin.com/in/liannie3/",
            portfolio: "https://liannie.app/",
        },
        {
            webp: "./static/th-2025/headshots/webp/nmesoma.webp",
            img: "./static/th-2025/headshots/jpg/nmesoma.jpg",
            name: "Nmesoma Duru",
            position: "Creative",
            linkedin: "https://www.linkedin.com/in/nmesoma-duru-283b15257/",
        },
        {
            webp: "./static/th-2025/headshots/webp/eric.webp",
            img: "./static/th-2025/headshots/jpg/eric.jpg",
            name: "Eric Li",
            position: "Tech",
            github: "https://github.com/ericli18",
            linkedin: "https://www.linkedin.com/in/ericli18/",
            portfolio: "https://ericwuli.com/",
        },
        {
            webp: "./static/th-2025/headshots/webp/aj.webp",
            img: "./static/th-2025/headshots/jpg/aj.jpg",
            name: "A.J Bamgbelu",
            position: "Tech",
            linkedin: "https://www.linkedin.com/in/ajbamgbelu/",
        },
        {
            webp: "./static/th-2025/headshots/webp/ashlee.webp",
            img: "./static/th-2025/headshots/jpg/ashlee.jpg",
            name: "Ashlee Ajala",
            position: "Logistics",
            linkedin: "https://www.linkedin.com/in/ashleeajala/",
        },
        {
            webp: "./static/th-2025/headshots/webp/claire.webp",
            img: "./static/th-2025/headshots/jpg/claire.jpg",
            name: "Claire Wang",
            position: "Creative",
            linkedin: "https://www.linkedin.com/in/chaire/",
        },
        {
            webp: "./static/th-2025/headshots/webp/keshav.webp",
            img: "./static/th-2025/headshots/jpg/keshav.jpg",
            name: "Keshav Dharshan",
            position: "Logistics",
            linkedin: "https://www.linkedin.com/in/keshav-dharshan-35a47524b/",
            github: "https://github.com/kdharshan0",
            portfolio: "https://keshavdharshan.com/",
        },
        {
            webp: "./static/th-2025/headshots/webp/monish.webp",
            img: "./static/th-2025/headshots/jpg/monish.jpg",
            name: "Monish Kanneboina",
            position: "Logistics",
            linkedin: "https://www.linkedin.com/in/monish-kanneboina/",
        },
        {
            webp: "./static/th-2025/headshots/webp/nikita.webp",
            img: "./static/th-2025/headshots/jpg/nikita.jpg",
            name: "Nikita Kelwada",
            position: "Logistics",
            linkedin: "https://www.linkedin.com/in/nikita-kelwada/",
        },
        {
            webp: "./static/th-2025/headshots/webp/blessing.webp",
            img: "./static/th-2025/headshots/jpg/blessing.jpg",
            name: "Blessing Onuoha",
            position: "Creative",
            linkedin: "https://www.linkedin.com/in/blxessing/",
        },
        {
            webp: "./static/th-2025/headshots/webp/justin.webp",
            img: "./static/th-2025/headshots/jpg/justin.jpg",
            name: "Justin Le",
            position: "Tech",
            github: "https://github.com/Ju5t1nL3",
            linkedin: "https://www.linkedin.com/in/justindtle/",
        },
    ],
};
